package types

const (
	REGISTERCLIENT  = "REGISTERCLIENT"
	REGISTERROOTDIR = "REGISTERROOTDIR"
	SYNCROOTDIR     = "SYNCROOTDIR"
	GETROOTDIRS     = "GETROOTDIRS"
	PLEASESYNC      = "PLEASESYNC"
	MUSTSYNC        = "MUSTSYNC"
	FORCESYNC       = "FORCESYNC"
	CONFLICT        = "CONFLICT"
	CONFLICTLIST    = "CONFLICTLIST"
	CHOOSEONE       = "CHOOSEONE"
	FULLSCAN        = "FULLSCAN"
	RESCAN          = "RESCAN"
)
